### ISSUE TITLE
USER STORY: View Recipe List

### ISSUE THREAD

**Issue by KseniaSOS** [KseniaSOS/sweet-code-blog#1]
As a **Site User** I can **view a list of the recipes** so that I can **select one to read**

### Acceptance Criteria
* The web page should display a list of all available recipes.
* Each recipe in the list must include a clickable button, to its full content.

### Tasks
- [x] Design and implement the recipe list view in HTML/CSS.
- [x] Integrate backend logic to fetch and display recipes.
- [x] Test the functionality
