### ISSUE TITLE
USER STORY: Create a Recipe

### ISSUE THREAD

**Issue by KseniaSOS** [KseniaSOS/sweet-code-blog#12]
As an **authenticated Site User** I can **create, read, update and delete my own Recipes** so that **I can contribute new content to the Sweet Code Blog and have a full control of my Recipes.**

### Acceptance Criteria
* Users should have full control over their recipes - creating, viewing, editing, and deleting.

### Tasks
- [x]  Implement Create, Read, Update, Delete (CRUD) operations for user recipes.
- [x] Ensure backend support for these operations.
- [x] Test the functionality.
