### ISSUE TITLE
USER STORY: Add Recipe to Favorite

### ISSUE THREAD

**Issue by KseniaSOS** [KseniaSOS/sweet-code-blog#13]
As a **Site User** I can **add Recipe to my favorite list** so that **I can save them on my page.**

### Acceptance Criteria
* Users can add / remove recipes to their favorites, reflected by a visible indicator (e.g., a star icon).
* Favorited recipes should be easily accessible on the user's profile page.

### Tasks
- [ ] Implement a 'Add to Favorites' feature on each recipe.
- [ ] Create a link in the navigation bar for favorited recipes.
- [ ] Create a page for favorited recipes.
- [ ] Ensure backend support for tracking user favorites.
- [ ] Test the functionality.
