### ISSUE TITLE
USER STORY: Recipe Category

### ISSUE THREAD

**Issue by KseniaSOS** [KseniaSOS/sweet-code-blog#14]
As a **Site User** I can **view recipe sorted by category** so that **I can narrow my search and focus on a particular category of personal interest.**

### Acceptance Criteria
* Users should be able to select categories to filter recipes.
* The filtered list should only show recipes from the selected category.

### Tasks
- [x] Implement category-based filtering in the recipe list view.
- [x] Modify backend to support fetching recipes by category.
- [x] Test the functionality.
