### ISSUE TITLE
USER STORY: User Registration

### ISSUE THREAD

**Issue by KseniaSOS** [KseniaSOS/sweet-code-blog#2]
As a **Site User** I can **easily create a profile** so that I can **post recipes to the blog, comment and like on other recipes.**

### Acceptance Criteria
* The registration form should include fields for username, email, and password.
* The form should validate input and provide error messages for invalid entries.
* Upon registration, the user should be provided with successful messages .
* Successful registration should give access to recipes, comment, and like recipes.

### Tasks
- [x] Design and implement user registration forms.
- [x] Implement backend logic for user registration.
- [x] Test the functionality
