### ISSUE TITLE
USER STORY: Manage blog

### ISSUE THREAD

**Issue by KseniaSOS** [KseniaSOS/sweet-code-blog#23]
As an **Admin** I can **create, read, update and delete Recipes** so that **I can manage my blog content.**

### Acceptance Criteria
* Admin can view a list of all recipes with details.
* Admin can create, edit, or delete a recipe, with changes reflected immediately.
* Admin should receive a confirmation prompt before deleting a recipe.

### Tasks
- [x] Implement CRUD operations.
- [x] Add confirmation dialogues for delete operations.
- [x] Test the functionality.
