### ISSUE TITLE
USER STORY: Create draft

### ISSUE THREAD

**Issue by KseniaSOS** [KseniaSOS/sweet-code-blog#24]
As a **Site Admin** I can **create draft** so that **to finalize content writing at a later date.**

### Acceptance Criteria
* Admin can save a recipe as a draft, which is not visible to site users.
* Drafts can be accessed and edited by the admin at any time.

### Tasks
- [x] Add a 'Save as Draft' option in the recipe creation/editing interface.
- [x] Implement backend logic to differentiate between drafts and published recipes.
- [x] Provide an option for admins to publish drafts.
- [x] Test the functionality.
