### ISSUE TITLE
USER STORY: View likes

### ISSUE THREAD

**Issue by KseniaSOS** [KseniaSOS/sweet-code-blog#25]
As a **Site User / Admin** I can **view the number of likes on each recipe** so that **I can see which is the most popular or viral.**

### Acceptance Criteria
* The number of likes should be displayed next to each recipe.
* The like count should update in real-time as users like/unlike the recipe.
* The like count should accurately reflect the total number of likes.

### Tasks
- [x] Integrate a like-counter for each recipe.
- [x] Update backend to track and serve like counts.
- [x] Test the functionality.
