### ISSUE TITLE
USER STORY: Add new Category

### ISSUE THREAD

**Issue by KseniaSOS** [KseniaSOS/sweet-code-blog#26]
As a **Site  Admin** I can **add a new category** so that **all users of the site could filter recipes on a particular category**

### Acceptance Criteria
* Admin can add a new category, which becomes available for filtering immediately.
* The category addition interface should be user-friendly and validate input.
* Newly added categories should be visible in the recipe filtering options.

### Tasks
- [x] Implement a feature in the admin panel to add new categories.
- [x] Modify the recipe filtering logic to incorporate new categories.
- [x] Test the functionality.
