### ISSUE TITLE
USER STORY: Like / unlike

### ISSUE THREAD

**Issue by KseniaSOS** [KseniaSOS/sweet-code-blog#3]
As a **Site User** I can **like or unlike a recipe** so that **I can interact with the content.**

### Acceptance Criteria
* Users should be able to like or unlike a recipe.
* The like status should be visually indicated (e.g., highlighted like button).

### Tasks
- [x] Implement like/unlike functionality.
- [x] Add icon for like identification.
- [x] Update backend to reflect the like status and number.
- [x] Test the functionality.
