### ISSUE TITLE
USER STORY: Login

### ISSUE THREAD

**Issue by KseniaSOS** [KseniaSOS/sweet-code-blog#4]
As a **Site User** I can **login to my registered account** so that **access create posts, the comment and like functionality.**

### Acceptance Criteria
* Users should be able to log in using their registered credentials.
* Upon login, users should have access to post, comment, and like functionalities.
* Unsuccessful login attempts should provide clear error messages.

### Tasks
- [x] Implement login functionality.
- [x] Invalid login attempts should display an error message without revealing which field (username or password) is incorrect.
- [x] Successful login should redirect the user to the homepage.
- [x] Test the functionality
