### ISSUE TITLE
USER STORY: Logout

### ISSUE THREAD

**Issue by KseniaSOS** [KseniaSOS/sweet-code-blog#5]
As a **Site User** I can **logout of my registered account** so that **keep my account safe from other users.**

### Acceptance Criteria
* Users should be able to easily log out.
* Post-logout, the user should not have access to profile-specific functionalities without logging in again.

### Tasks
- [x] Implement logout functionality.
- [x] Add confirmation page, if user wants to logout.
- [x] Provide feedback for logout success.
- [x] Test the functionality.
