### ISSUE TITLE
USER STORY: Personal page view

### ISSUE THREAD

**Issue by KseniaSOS** [KseniaSOS/sweet-code-blog#6]
As an **authenticated Site User** I can **view my personal page with recipes** so that **I can view my own content concisely and access it for the purpose of editing.**

### Acceptance Criteria
* The personal page must display all recipes posted by the user.
* Users should be able to view, edit, and delete their recipes from this page.

### Tasks
- [x] Create a personal dashboard for users.
- [x] Display user's posted recipes and provide editing options.
- [x] Test the functionality.
