### ISSUE TITLE
USER STORY: Comment a Recipe

### ISSUE THREAD

**Issue by KseniaSOS** [KseniaSOS/sweet-code-blog#7]
As an **authenticated Site User** I can **leave comments on a recipe** so that **I can be involved in the conversation.**

### Acceptance Criteria
* Users should be able to post comments on recipes.
* Posted comments should be visible immediately after admin approval.

### Tasks
- [x] Submitted comments should appear on in comments section after admin approval.
- [x] The comment field should be cleared after a successful submission.
- [x] Ensure backend supports adding new comments.
- [x] Test the functionality.
