### ISSUE TITLE
USER STORY: Approve/disapprove comments

### ISSUE THREAD

**Issue by KseniaSOS** [KseniaSOS/sweet-code-blog#9]
As a **Site Admin** I can **approve or disapprove comments** so that **I can filter out objectionable comments.**

### Acceptance Criteria
* Admin can view and moderate all comments.
* Each comment should have an 'Approve' and 'Disapprove' option.
* Disapproved comments should not be visible to site users.

### Tasks
- [x] Implement a feature in the admin panel for comment moderation.
- [x] Implement backend logic for comment approval status.
- [x] Test the functionality.
